// lib/pdf/imageRegistry.ts
// AUTO-GENERATED by scripts/generate-image-registry.mjs
// DO NOT edit manually — re-run the script after adding new images.

export type ImageDietary = 'vegetarian' | 'non-vegetarian' | 'vegan' | 'egg' | 'seafood' | 'unknown';

export interface MenuImageEntry {
  id: string;
  dishId?: string;
  filename: string;
  name: string;
  family: string;
  keywords: string[];
  cuisine: string[];
  category: string[];
  dietary: ImageDietary;
  suitableFor: string[];
  isValidQuality: boolean;
  fileSizeBytes: number;
  source?: 'manual' | 'generated';
  generatedAt?: string;
  provider?: string;
  model?: string;
  promptVersion?: string;
}

export const IMAGE_REGISTRY: MenuImageEntry[] = [
  {
    "id": "butter-chicken",
    "filename": "generated/butter-chicken.jpg",
    "name": "Butter Chicken",
    "family": "CHICKEN",
    "keywords": [
      "butter",
      "chicken"
    ],
    "cuisine": [
      "indian",
      "punjabi",
      "north-indian"
    ],
    "category": [
      "main-course",
      "starter"
    ],
    "dietary": "non-vegetarian",
    "suitableFor": [
      "indian-counter",
      "main-course",
      "non-veg-counter"
    ],
    "isValidQuality": true,
    "fileSizeBytes": 858616,
    "source": "generated"
  },
  {
    "id": "chicken-biryani",
    "filename": "generated/chicken-biryani.jpg",
    "name": "Chicken Biryani",
    "family": "CHICKEN",
    "keywords": [
      "chicken",
      "biryani"
    ],
    "cuisine": [
      "indian",
      "mughlai",
      "awadhi",
      "hyderabadi"
    ],
    "category": [
      "starter",
      "main-course",
      "rice"
    ],
    "dietary": "non-vegetarian",
    "suitableFor": [
      "non-veg-counter",
      "main-course",
      "rice-counter",
      "biryani-counter",
      "hero"
    ],
    "isValidQuality": true,
    "fileSizeBytes": 832397,
    "source": "generated"
  },
  {
    "id": "dish-0301",
    "dishId": "dish-0301",
    "filename": "generated/dal-makhani.jpg",
    "name": "Dal makhani",
    "family": "DAL",
    "keywords": [
      "dal",
      "makhani"
    ],
    "cuisine": [
      "indian",
      "north-indian",
      "punjabi"
    ],
    "category": [
      "main",
      "main-course",
      "accompaniment"
    ],
    "dietary": "vegetarian",
    "suitableFor": [
      "mains-indian",
      "indian-counter",
      "main-course"
    ],
    "isValidQuality": true,
    "fileSizeBytes": 732684,
    "source": "generated"
  },
  {
    "id": "dish-0001",
    "dishId": "dish-0001",
    "filename": "generated/dish-0001.jpg",
    "name": "Assorted bite size sandwich",
    "family": "SANDWICH",
    "keywords": [
      "assorted",
      "bite",
      "size",
      "sandwich"
    ],
    "cuisine": [
      "continental",
      "western"
    ],
    "category": [
      "starter",
      "snack",
      "canapes"
    ],
    "dietary": "vegetarian",
    "suitableFor": [
      "arrival-bites",
      "welcome-bites",
      "starter"
    ],
    "isValidQuality": true,
    "fileSizeBytes": 846617,
    "source": "generated",
    "generatedAt": "2026-09-02T07:17:56.594Z",
    "provider": "antigravity"
  },
  {
    "id": "dish-0002",
    "dishId": "dish-0002",
    "filename": "generated/dish-0002.jpg",
    "name": "Mushroom vol au vents",
    "family": "GENERAL",
    "keywords": [
      "mushroom",
      "vol",
      "au",
      "vents"
    ],
    "cuisine": [
      "continental"
    ],
    "category": [
      "starter"
    ],
    "dietary": "vegetarian",
    "suitableFor": [
      "arrival-bites",
      "appetizer-rotation",
      "passed-hors"
    ],
    "isValidQuality": true,
    "fileSizeBytes": 746630,
    "source": "generated",
    "generatedAt": "2026-09-02T07:17:56.598Z",
    "provider": "antigravity"
  },
  {
    "id": "dish-0003",
    "dishId": "dish-0003",
    "filename": "generated/dish-0003.jpg",
    "name": "Spinach & corn quiche",
    "family": "GENERAL",
    "keywords": [
      "spinach",
      "corn",
      "quiche"
    ],
    "cuisine": [
      "continental"
    ],
    "category": [
      "starter"
    ],
    "dietary": "vegetarian",
    "suitableFor": [
      "arrival-bites",
      "appetizer-rotation",
      "passed-hors"
    ],
    "isValidQuality": true,
    "fileSizeBytes": 769848,
    "source": "generated",
    "generatedAt": "2026-09-02T07:17:00.170Z",
    "provider": "antigravity"
  },
  {
    "id": "dish-0004",
    "dishId": "dish-0004",
    "filename": "generated/dish-0004.jpg",
    "name": "Cocktail samosa",
    "family": "SAMOSA",
    "keywords": [
      "cocktail",
      "samosa"
    ],
    "cuisine": [
      "continental",
      "indian",
      "north-indian"
    ],
    "category": [
      "starter",
      "snack",
      "chaat"
    ],
    "dietary": "vegetarian",
    "suitableFor": [
      "arrival-bites",
      "appetizer-rotation",
      "passed-hors",
      "starter",
      "chaat-counter",
      "welcome-bites"
    ],
    "isValidQuality": true,
    "fileSizeBytes": 730276,
    "source": "generated",
    "generatedAt": "2026-09-02T07:17:56.600Z",
    "provider": "antigravity"
  },
  {
    "id": "dish-0005",
    "dishId": "dish-0005",
    "filename": "generated/dish-0005.jpg",
    "name": "Assorted bater-fried crispies",
    "family": "GENERAL",
    "keywords": [
      "assorted",
      "bater",
      "fried",
      "crispies"
    ],
    "cuisine": [
      "continental"
    ],
    "category": [
      "starter"
    ],
    "dietary": "vegetarian",
    "suitableFor": [
      "arrival-bites"
    ],
    "isValidQuality": true,
    "fileSizeBytes": 901250,
    "source": "generated",
    "generatedAt": "2026-09-02T07:17:00.176Z",
    "provider": "antigravity"
  },
  {
    "id": "dish-0006",
    "dishId": "dish-0006",
    "filename": "generated/dish-0006.jpg",
    "name": "Chilli cheese toast",
    "family": "GENERAL",
    "keywords": [
      "chilli",
      "cheese",
      "toast"
    ],
    "cuisine": [
      "continental"
    ],
    "category": [
      "starter"
    ],
    "dietary": "vegetarian",
    "suitableFor": [
      "arrival-bites",
      "appetizer-rotation",
      "passed-hors"
    ],
    "isValidQuality": true,
    "fileSizeBytes": 795430,
    "source": "generated",
    "generatedAt": "2026-09-02T07:17:00.179Z",
    "provider": "antigravity"
  },
  {
    "id": "dish-0007",
    "dishId": "dish-0007",
    "filename": "generated/dish-0007.jpg",
    "name": "Mozzarella, confit pepper & parsley croquettes",
    "family": "GENERAL",
    "keywords": [
      "mozzarella",
      "confit",
      "pepper",
      "parsley",
      "croquettes"
    ],
    "cuisine": [
      "continental"
    ],
    "category": [
      "starter"
    ],
    "dietary": "vegetarian",
    "suitableFor": [
      "arrival-bites",
      "appetizer-rotation",
      "passed-hors"
    ],
    "isValidQuality": true,
    "fileSizeBytes": 759161,
    "source": "generated",
    "generatedAt": "2026-09-02T07:17:00.182Z",
    "provider": "antigravity"
  },
  {
    "id": "dish-0008",
    "dishId": "dish-0008",
    "filename": "generated/dish-0008.jpg",
    "name": "Kaju katli",
    "family": "GENERAL",
    "keywords": [
      "kaju",
      "katli"
    ],
    "cuisine": [
      "continental"
    ],
    "category": [
      "starter"
    ],
    "dietary": "vegetarian",
    "suitableFor": [
      "arrival-bites"
    ],
    "isValidQuality": true,
    "fileSizeBytes": 806102,
    "source": "generated",
    "generatedAt": "2026-09-02T07:17:00.186Z",
    "provider": "antigravity"
  },
  {
    "id": "dish-0009",
    "dishId": "dish-0009",
    "filename": "generated/dish-0009.jpg",
    "name": "Dry fruit cake",
    "family": "GENERAL",
    "keywords": [
      "dry",
      "fruit",
      "cake"
    ],
    "cuisine": [
      "continental"
    ],
    "category": [
      "starter"
    ],
    "dietary": "vegetarian",
    "suitableFor": [
      "arrival-bites"
    ],
    "isValidQuality": true,
    "fileSizeBytes": 765844,
    "source": "generated",
    "generatedAt": "2026-09-02T07:17:56.602Z",
    "provider": "antigravity"
  },
  {
    "id": "dish-0010",
    "dishId": "dish-0010",
    "filename": "generated/dish-0010.jpg",
    "name": "Tea & Coffee",
    "family": "GENERAL",
    "keywords": [
      "tea",
      "coffee"
    ],
    "cuisine": [
      "continental"
    ],
    "category": [
      "starter"
    ],
    "dietary": "vegetarian",
    "suitableFor": [
      "arrival-bites",
      "indian-desserts",
      "western-desserts"
    ],
    "isValidQuality": true,
    "fileSizeBytes": 780302,
    "source": "generated",
    "generatedAt": "2026-09-02T07:17:56.606Z",
    "provider": "antigravity"
  },
  {
    "id": "dish-0011",
    "dishId": "dish-0011",
    "filename": "generated/dish-0011.jpg",
    "name": "Mineral water - 200 ml",
    "family": "GENERAL",
    "keywords": [
      "mineral",
      "water",
      "200",
      "ml"
    ],
    "cuisine": [
      "continental"
    ],
    "category": [
      "starter"
    ],
    "dietary": "vegetarian",
    "suitableFor": [
      "arrival-bites",
      "beverage-lounge"
    ],
    "isValidQuality": true,
    "fileSizeBytes": 659525,
    "source": "generated",
    "generatedAt": "2026-09-02T07:17:56.609Z",
    "provider": "antigravity"
  },
  {
    "id": "dish-0012",
    "dishId": "dish-0012",
    "filename": "generated/dish-0012.jpg",
    "name": "Wasabi prawns",
    "family": "GENERAL",
    "keywords": [
      "wasabi",
      "prawns"
    ],
    "cuisine": [
      "global"
    ],
    "category": [
      "starter"
    ],
    "dietary": "non-vegetarian",
    "suitableFor": [
      "passed-hors"
    ],
    "isValidQuality": true,
    "fileSizeBytes": 748351,
    "source": "generated",
    "generatedAt": "2026-09-02T07:17:56.616Z",
    "provider": "antigravity"
  },
  {
    "id": "dish-0013",
    "dishId": "dish-0013",
    "filename": "generated/dish-0013.jpg",
    "name": "Amritsari fish with edamame, figs & prunes chutney",
    "family": "FISH",
    "keywords": [
      "amritsari",
      "fish",
      "with",
      "edamame",
      "figs",
      "prunes",
      "chutney"
    ],
    "cuisine": [
      "global"
    ],
    "category": [
      "starter",
      "main-course",
      "seafood"
    ],
    "dietary": "non-vegetarian",
    "suitableFor": [
      "passed-hors",
      "appetizer-rotation",
      "arrival-bites",
      "seafood-counter",
      "starter",
      "main-course"
    ],
    "isValidQuality": true,
    "fileSizeBytes": 784156,
    "source": "generated",
    "generatedAt": "2026-09-02T07:17:56.618Z",
    "provider": "antigravity"
  },
  {
    "id": "dish-0014",
    "dishId": "dish-0014",
    "filename": "generated/dish-0014.jpg",
    "name": "Philadelphia cheese marinated chicken tikka",
    "family": "CHICKEN",
    "keywords": [
      "philadelphia",
      "cheese",
      "marinated",
      "chicken",
      "tikka"
    ],
    "cuisine": [
      "global",
      "indian",
      "north-indian",
      "mughlai"
    ],
    "category": [
      "starter",
      "main-course"
    ],
    "dietary": "non-vegetarian",
    "suitableFor": [
      "passed-hors",
      "appetizer-rotation",
      "arrival-bites",
      "non-veg-counter",
      "main-course",
      "starter",
      "live-counter",
      "tandoor-counter"
    ],
    "isValidQuality": true,
    "fileSizeBytes": 111869,
    "source": "generated",
    "generatedAt": "2026-09-01T08:40:36.181Z",
    "provider": "antigravity",
    "model": "mock-svg-v1",
    "promptVersion": "v1.0"
  },
  {
    "id": "dish-0015",
    "dishId": "dish-0015",
    "filename": "generated/dish-0015.jpg",
    "name": "Japanese chicken karage",
    "family": "CHICKEN",
    "keywords": [
      "japanese",
      "chicken",
      "karage"
    ],
    "cuisine": [
      "global",
      "indian"
    ],
    "category": [
      "starter",
      "main-course"
    ],
    "dietary": "non-vegetarian",
    "suitableFor": [
      "passed-hors",
      "appetizer-rotation",
      "arrival-bites",
      "non-veg-counter",
      "main-course"
    ],
    "isValidQuality": true,
    "fileSizeBytes": 125118,
    "source": "generated",
    "generatedAt": "2026-09-01T08:40:36.191Z",
    "provider": "antigravity",
    "model": "mock-svg-v1",
    "promptVersion": "v1.0"
  },
  {
    "id": "dish-0016",
    "dishId": "dish-0016",
    "filename": "generated/dish-0016.jpg",
    "name": "Dragon chicken",
    "family": "CHICKEN",
    "keywords": [
      "dragon",
      "chicken"
    ],
    "cuisine": [
      "global",
      "indian"
    ],
    "category": [
      "starter",
      "main-course"
    ],
    "dietary": "non-vegetarian",
    "suitableFor": [
      "passed-hors",
      "non-veg-counter",
      "main-course"
    ],
    "isValidQuality": true,
    "fileSizeBytes": 145568,
    "source": "generated",
    "generatedAt": "2026-09-02T08:35:25.722Z",
    "provider": "antigravity"
  },
  {
    "id": "dish-0017",
    "dishId": "dish-0017",
    "filename": "generated/dish-0017.jpg",
    "name": "Rampuri seekh kebab",
    "family": "GENERAL",
    "keywords": [
      "rampuri",
      "seekh",
      "kebab"
    ],
    "cuisine": [
      "global",
      "indian",
      "mughlai",
      "awadhi"
    ],
    "category": [
      "starter",
      "live-counter"
    ],
    "dietary": "non-vegetarian",
    "suitableFor": [
      "passed-hors",
      "live-counter",
      "mughlai-counter",
      "starter"
    ],
    "isValidQuality": true,
    "fileSizeBytes": 127920,
    "source": "generated",
    "generatedAt": "2026-09-02T08:35:25.723Z",
    "provider": "antigravity"
  },
  {
    "id": "dish-0018",
    "dishId": "dish-0018",
    "filename": "generated/dish-0018.jpg",
    "name": "Gamberoni a-la-plancha",
    "family": "GENERAL",
    "keywords": [
      "gamberoni",
      "la",
      "plancha"
    ],
    "cuisine": [
      "global"
    ],
    "category": [
      "starter"
    ],
    "dietary": "non-vegetarian",
    "suitableFor": [
      "passed-hors",
      "appetizer-rotation",
      "pasta-studio",
      "pizza-oven"
    ],
    "isValidQuality": true,
    "fileSizeBytes": 162127,
    "source": "generated",
    "generatedAt": "2026-09-02T08:35:25.723Z",
    "provider": "antigravity"
  },
  {
    "id": "dish-0019",
    "dishId": "dish-0019",
    "filename": "generated/dish-0019.jpg",
    "name": "Fenugreek fish tikka with coriander chilly dip",
    "family": "FISH",
    "keywords": [
      "fenugreek",
      "fish",
      "tikka",
      "with",
      "coriander",
      "chilly",
      "dip"
    ],
    "cuisine": [
      "global",
      "indian",
      "north-indian",
      "mughlai"
    ],
    "category": [
      "starter",
      "main-course",
      "seafood"
    ],
    "dietary": "non-vegetarian",
    "suitableFor": [
      "passed-hors",
      "appetizer-rotation",
      "arrival-bites",
      "seafood-counter",
      "starter",
      "main-course",
      "live-counter",
      "tandoor-counter"
    ],
    "isValidQuality": true,
    "fileSizeBytes": 117425,
    "source": "generated",
    "generatedAt": "2026-09-02T08:35:25.723Z",
    "provider": "antigravity"
  },
  {
    "id": "dish-0020",
    "dishId": "dish-0020",
    "filename": "generated/dish-0020.jpg",
    "name": "Duck spring roll",
    "family": "GENERAL",
    "keywords": [
      "duck",
      "spring",
      "roll"
    ],
    "cuisine": [
      "global"
    ],
    "category": [
      "starter"
    ],
    "dietary": "non-vegetarian",
    "suitableFor": [
      "passed-hors",
      "appetizer-rotation",
      "arrival-bites"
    ],
    "isValidQuality": true,
    "fileSizeBytes": 99991,
    "source": "generated",
    "generatedAt": "2026-09-02T08:35:25.723Z",
    "provider": "antigravity"
  },
  {
    "id": "dish-0021",
    "dishId": "dish-0021",
    "filename": "generated/dish-0021.jpg",
    "name": "Burnt garlic thyme chicken tikka",
    "family": "CHICKEN",
    "keywords": [
      "burnt",
      "garlic",
      "thyme",
      "chicken",
      "tikka"
    ],
    "cuisine": [
      "global",
      "indian",
      "north-indian",
      "mughlai"
    ],
    "category": [
      "starter",
      "main-course"
    ],
    "dietary": "non-vegetarian",
    "suitableFor": [
      "passed-hors",
      "appetizer-rotation",
      "non-veg-counter",
      "main-course",
      "starter",
      "live-counter",
      "tandoor-counter"
    ],
    "isValidQuality": true,
    "fileSizeBytes": 157230,
    "source": "generated",
    "generatedAt": "2026-09-02T08:35:25.723Z",
    "provider": "antigravity"
  },
  {
    "id": "dish-0022",
    "dishId": "dish-0022",
    "filename": "generated/dish-0022.jpg",
    "name": "Chilly garlic lamb",
    "family": "MUTTON",
    "keywords": [
      "chilly",
      "garlic",
      "lamb"
    ],
    "cuisine": [
      "global"
    ],
    "category": [
      "starter",
      "main-course"
    ],
    "dietary": "non-vegetarian",
    "suitableFor": [
      "passed-hors",
      "appetizer-rotation",
      "arrival-bites",
      "non-veg-counter",
      "main-course"
    ],
    "isValidQuality": true,
    "fileSizeBytes": 150350,
    "source": "generated",
    "generatedAt": "2026-09-01T08:40:36.196Z",
    "provider": "antigravity",
    "model": "mock-svg-v1",
    "promptVersion": "v1.0"
  },
  {
    "id": "dish-0023",
    "dishId": "dish-0023",
    "filename": "generated/dish-0023.jpg",
    "name": "Goan pepper lamb",
    "family": "MUTTON",
    "keywords": [
      "goan",
      "pepper",
      "lamb"
    ],
    "cuisine": [
      "global"
    ],
    "category": [
      "starter",
      "main-course"
    ],
    "dietary": "non-vegetarian",
    "suitableFor": [
      "passed-hors",
      "appetizer-rotation",
      "arrival-bites",
      "non-veg-counter",
      "main-course"
    ],
    "isValidQuality": true,
    "fileSizeBytes": 142909,
    "source": "generated",
    "generatedAt": "2026-09-02T08:35:25.723Z",
    "provider": "antigravity"
  },
  {
    "id": "dish-0024",
    "dishId": "dish-0024",
    "filename": "generated/dish-0024.jpg",
    "name": "Edamame seekh kebab",
    "family": "GENERAL",
    "keywords": [
      "edamame",
      "seekh",
      "kebab"
    ],
    "cuisine": [
      "global",
      "indian",
      "mughlai",
      "awadhi"
    ],
    "category": [
      "starter",
      "live-counter"
    ],
    "dietary": "vegetarian",
    "suitableFor": [
      "passed-hors",
      "appetizer-rotation",
      "live-counter",
      "mughlai-counter",
      "starter"
    ],
    "isValidQuality": true,
    "fileSizeBytes": 142286,
    "source": "generated",
    "generatedAt": "2026-09-02T08:35:25.723Z",
    "provider": "antigravity"
  },
  {
    "id": "dish-0025",
    "dishId": "dish-0025",
    "filename": "generated/dish-0025.jpg",
    "name": "Charcoal roasted mushroom",
    "family": "GENERAL",
    "keywords": [
      "charcoal",
      "roasted",
      "mushroom"
    ],
    "cuisine": [
      "global"
    ],
    "category": [
      "starter"
    ],
    "dietary": "vegetarian",
    "suitableFor": [
      "passed-hors",
      "appetizer-rotation"
    ],
    "isValidQuality": true,
    "fileSizeBytes": 138000,
    "source": "generated",
    "generatedAt": "2026-09-02T08:35:25.723Z",
    "provider": "antigravity"
  },
  {
    "id": "dish-0026",
    "dishId": "dish-0026",
    "filename": "generated/dish-0026.jpg",
    "name": "Achari paneer tikka",
    "family": "PANEER",
    "keywords": [
      "achari",
      "paneer",
      "tikka"
    ],
    "cuisine": [
      "global",
      "indian",
      "north-indian",
      "mughlai"
    ],
    "category": [
      "starter",
      "main-course"
    ],
    "dietary": "vegetarian",
    "suitableFor": [
      "passed-hors",
      "appetizer-rotation",
      "arrival-bites",
      "starter",
      "indian-counter",
      "mughlai-counter",
      "live-counter",
      "tandoor-counter"
    ],
    "isValidQuality": true,
    "fileSizeBytes": 142991,
    "source": "generated",
    "generatedAt": "2026-09-01T08:40:36.201Z",
    "provider": "antigravity",
    "model": "mock-svg-v1",
    "promptVersion": "v1.0"
  },
  {
    "id": "dish-0027",
    "dishId": "dish-0027",
    "filename": "generated/dish-0027.jpg",
    "name": "Turkish sigara börek",
    "family": "GENERAL",
    "keywords": [
      "turkish",
      "sigara",
      "borek"
    ],
    "cuisine": [
      "global"
    ],
    "category": [
      "starter"
    ],
    "dietary": "vegetarian",
    "suitableFor": [
      "passed-hors"
    ],
    "isValidQuality": true,
    "fileSizeBytes": 127407,
    "source": "generated",
    "generatedAt": "2026-09-02T08:35:25.723Z",
    "provider": "antigravity"
  },
  {
    "id": "dish-0028",
    "dishId": "dish-0028",
    "filename": "generated/dish-0028.jpg",
    "name": "Bang bang broccoli",
    "family": "GENERAL",
    "keywords": [
      "bang",
      "broccoli"
    ],
    "cuisine": [
      "global"
    ],
    "category": [
      "starter"
    ],
    "dietary": "vegetarian",
    "suitableFor": [
      "passed-hors",
      "appetizer-rotation",
      "arrival-bites"
    ],
    "isValidQuality": true,
    "fileSizeBytes": 165570,
    "source": "generated",
    "generatedAt": "2026-09-02T08:35:25.723Z",
    "provider": "antigravity"
  },
  {
    "id": "dish-0029",
    "dishId": "dish-0029",
    "filename": "generated/dish-0029.jpg",
    "name": "Figs & walnut kebab",
    "family": "GENERAL",
    "keywords": [
      "figs",
      "walnut",
      "kebab"
    ],
    "cuisine": [
      "global",
      "indian",
      "mughlai",
      "awadhi"
    ],
    "category": [
      "starter",
      "live-counter"
    ],
    "dietary": "vegetarian",
    "suitableFor": [
      "passed-hors",
      "appetizer-rotation",
      "starter",
      "live-counter",
      "mughlai-counter"
    ],
    "isValidQuality": true,
    "fileSizeBytes": 152196,
    "source": "generated",
    "generatedAt": "2026-09-02T08:35:25.723Z",
    "provider": "antigravity"
  },
  {
    "id": "dish-0030",
    "dishId": "dish-0030",
    "filename": "generated/dish-0030.jpg",
    "name": "Ricotta hung curd kebab",
    "family": "GENERAL",
    "keywords": [
      "ricotta",
      "hung",
      "curd",
      "kebab"
    ],
    "cuisine": [
      "global",
      "indian",
      "mughlai",
      "awadhi"
    ],
    "category": [
      "starter",
      "live-counter"
    ],
    "dietary": "vegetarian",
    "suitableFor": [
      "passed-hors",
      "starter",
      "live-counter",
      "mughlai-counter"
    ],
    "isValidQuality": true,
    "fileSizeBytes": 107409,
    "source": "generated",
    "generatedAt": "2026-09-02T08:35:25.723Z",
    "provider": "antigravity"
  },
  {
    "id": "dish-0031",
    "dishId": "dish-0031",
    "filename": "generated/dish-0031.jpg",
    "name": "Butter chilli garlic crispy water chestnut",
    "family": "GENERAL",
    "keywords": [
      "butter",
      "chilli",
      "garlic",
      "crispy",
      "water",
      "chestnut"
    ],
    "cuisine": [
      "global",
      "indian",
      "punjabi",
      "north-indian"
    ],
    "category": [
      "starter",
      "main-course"
    ],
    "dietary": "vegetarian",
    "suitableFor": [
      "passed-hors",
      "appetizer-rotation",
      "arrival-bites",
      "indian-counter",
      "main-course"
    ],
    "isValidQuality": true,
    "fileSizeBytes": 151465,
    "source": "generated",
    "generatedAt": "2026-09-02T08:35:25.723Z",
    "provider": "antigravity"
  },
  {
    "id": "dish-0032",
    "dishId": "dish-0032",
    "filename": "generated/dish-0032.jpg",
    "name": "Truffle butter drizzled soya malai tikka",
    "family": "GENERAL",
    "keywords": [
      "truffle",
      "butter",
      "drizzled",
      "soya",
      "malai",
      "tikka"
    ],
    "cuisine": [
      "global",
      "indian",
      "punjabi",
      "north-indian",
      "mughlai"
    ],
    "category": [
      "starter",
      "main-course"
    ],
    "dietary": "vegetarian",
    "suitableFor": [
      "passed-hors",
      "appetizer-rotation",
      "arrival-bites",
      "indian-counter",
      "main-course",
      "starter",
      "live-counter",
      "tandoor-counter"
    ],
    "isValidQuality": true,
    "fileSizeBytes": 119478,
    "source": "generated",
    "generatedAt": "2026-09-02T08:35:25.723Z",
    "provider": "antigravity"
  },
  {
    "id": "dish-0033",
    "dishId": "dish-0033",
    "filename": "generated/dish-0033.jpg",
    "name": "Crispy honey lotus stem",
    "family": "GENERAL",
    "keywords": [
      "crispy",
      "honey",
      "lotus",
      "stem"
    ],
    "cuisine": [
      "global"
    ],
    "category": [
      "starter"
    ],
    "dietary": "vegetarian",
    "suitableFor": [
      "passed-hors",
      "appetizer-rotation",
      "arrival-bites"
    ],
    "isValidQuality": true,
    "fileSizeBytes": 172382,
    "source": "generated",
    "generatedAt": "2026-09-02T08:35:25.723Z",
    "provider": "antigravity"
  },
  {
    "id": "dish-0034",
    "dishId": "dish-0034",
    "filename": "generated/dish-0034.jpg",
    "name": "Savoury tarts of leeks & onion",
    "family": "GENERAL",
    "keywords": [
      "savoury",
      "tarts",
      "of",
      "leeks",
      "onion"
    ],
    "cuisine": [
      "global"
    ],
    "category": [
      "starter"
    ],
    "dietary": "vegetarian",
    "suitableFor": [
      "passed-hors",
      "appetizer-rotation"
    ],
    "isValidQuality": true,
    "fileSizeBytes": 132915,
    "source": "generated",
    "generatedAt": "2026-09-02T08:35:25.723Z",
    "provider": "antigravity"
  },
  {
    "id": "dish-0035",
    "dishId": "dish-0035",
    "filename": "generated/dish-0035.jpg",
    "name": "Kung pao potatoes with spring onion",
    "family": "GENERAL",
    "keywords": [
      "kung",
      "pao",
      "potatoes",
      "with",
      "spring",
      "onion"
    ],
    "cuisine": [
      "global"
    ],
    "category": [
      "starter"
    ],
    "dietary": "vegetarian",
    "suitableFor": [
      "passed-hors",
      "appetizer-rotation",
      "arrival-bites"
    ],
    "isValidQuality": true,
    "fileSizeBytes": 145142,
    "source": "generated",
    "generatedAt": "2026-09-02T08:35:25.723Z",
    "provider": "antigravity"
  },
  {
    "id": "dish-0036",
    "dishId": "dish-0036",
    "filename": "generated/dish-0036.jpg",
    "name": "Gol gappa ( meetha, pudhina, hing, guava)",
    "family": "GENERAL",
    "keywords": [
      "gol",
      "gappa",
      "meetha",
      "pudhina",
      "hing",
      "guava"
    ],
    "cuisine": [
      "indian street"
    ],
    "category": [
      "starter"
    ],
    "dietary": "vegetarian",
    "suitableFor": [
      "chaat-atelier"
    ],
    "isValidQuality": true,
    "fileSizeBytes": 174559,
    "source": "generated",
    "generatedAt": "2026-09-02T08:35:25.723Z",
    "provider": "antigravity"
  },
  {
    "id": "dish-0037",
    "dishId": "dish-0037",
    "filename": "generated/dish-0037.jpg",
    "name": "Haridwar patta pe karari aloo tikki",
    "family": "GENERAL",
    "keywords": [
      "haridwar",
      "patta",
      "pe",
      "karari",
      "aloo",
      "tikki"
    ],
    "cuisine": [
      "indian street",
      "indian"
    ],
    "category": [
      "starter",
      "main-course"
    ],
    "dietary": "vegetarian",
    "suitableFor": [
      "chaat-atelier",
      "starter",
      "indian-counter"
    ],
    "isValidQuality": true,
    "fileSizeBytes": 176227,
    "source": "generated",
    "generatedAt": "2026-09-02T08:35:25.723Z",
    "provider": "antigravity"
  },
  {
    "id": "dish-0038",
    "dishId": "dish-0038",
    "filename": "generated/dish-0038.jpg",
    "name": "Palak patte ki chaat",
    "family": "GENERAL",
    "keywords": [
      "palak",
      "patte",
      "ki",
      "chaat"
    ],
    "cuisine": [
      "indian street",
      "indian",
      "north-indian"
    ],
    "category": [
      "starter",
      "chaat"
    ],
    "dietary": "vegetarian",
    "suitableFor": [
      "chaat-atelier",
      "chaat-counter",
      "starter",
      "welcome-bites"
    ],
    "isValidQuality": true,
    "fileSizeBytes": 180679,
    "source": "generated",
    "generatedAt": "2026-09-02T08:35:25.723Z",
    "provider": "antigravity"
  },
  {
    "id": "dish-0039",
    "dishId": "dish-0039",
    "filename": "generated/dish-0039.jpg",
    "name": "Avocado sev puri disc",
    "family": "GENERAL",
    "keywords": [
      "avocado",
      "sev",
      "puri",
      "disc"
    ],
    "cuisine": [
      "indian street"
    ],
    "category": [
      "starter"
    ],
    "dietary": "vegetarian",
    "suitableFor": [
      "chaat-atelier"
    ],
    "isValidQuality": true,
    "fileSizeBytes": 117246,
    "source": "generated",
    "generatedAt": "2026-09-02T08:35:25.723Z",
    "provider": "antigravity"
  },
  {
    "id": "dish-0040",
    "dishId": "dish-0040",
    "filename": "generated/dish-0040.jpg",
    "name": "Matra : home made kulcha",
    "family": "GENERAL",
    "keywords": [
      "matra",
      "home",
      "made",
      "kulcha"
    ],
    "cuisine": [
      "indian street"
    ],
    "category": [
      "starter"
    ],
    "dietary": "vegetarian",
    "suitableFor": [
      "chaat-atelier"
    ],
    "isValidQuality": true,
    "fileSizeBytes": 180186,
    "source": "generated",
    "generatedAt": "2026-09-02T08:35:25.723Z",
    "provider": "antigravity"
  },
  {
    "id": "dish-0041",
    "dishId": "dish-0041",
    "filename": "generated/dish-0041.jpg",
    "name": "Lavaash",
    "family": "GENERAL",
    "keywords": [
      "lavaash"
    ],
    "cuisine": [
      "global"
    ],
    "category": [
      "starter"
    ],
    "dietary": "vegetarian",
    "suitableFor": [
      "grazing-table"
    ],
    "isValidQuality": true,
    "fileSizeBytes": 131625,
    "source": "generated",
    "generatedAt": "2026-09-02T08:35:25.723Z",
    "provider": "antigravity"
  },
  {
    "id": "dish-0042",
    "dishId": "dish-0042",
    "filename": "generated/dish-0042.jpg",
    "name": "Cracker",
    "family": "GENERAL",
    "keywords": [
      "cracker"
    ],
    "cuisine": [
      "global"
    ],
    "category": [
      "starter"
    ],
    "dietary": "vegetarian",
    "suitableFor": [
      "grazing-table"
    ],
    "isValidQuality": true,
    "fileSizeBytes": 154644,
    "source": "generated",
    "generatedAt": "2026-09-02T08:35:25.723Z",
    "provider": "antigravity"
  },
  {
    "id": "dish-0043",
    "dishId": "dish-0043",
    "filename": "generated/dish-0043.jpg",
    "name": "Garlic toast",
    "family": "GENERAL",
    "keywords": [
      "garlic",
      "toast"
    ],
    "cuisine": [
      "global"
    ],
    "category": [
      "starter"
    ],
    "dietary": "vegetarian",
    "suitableFor": [
      "grazing-table"
    ],
    "isValidQuality": true,
    "fileSizeBytes": 118447,
    "source": "generated",
    "generatedAt": "2026-09-02T08:35:25.723Z",
    "provider": "antigravity"
  },
  {
    "id": "dish-0044",
    "dishId": "dish-0044",
    "filename": "generated/dish-0044.jpg",
    "name": "Focaccia bread",
    "family": "GENERAL",
    "keywords": [
      "focaccia",
      "bread"
    ],
    "cuisine": [
      "global"
    ],
    "category": [
      "starter"
    ],
    "dietary": "vegetarian",
    "suitableFor": [
      "grazing-table"
    ],
    "isValidQuality": true,
    "fileSizeBytes": 155509,
    "source": "generated",
    "generatedAt": "2026-09-02T08:35:25.723Z",
    "provider": "antigravity"
  },
  {
    "id": "dish-0045",
    "dishId": "dish-0045",
    "filename": "generated/dish-0045.jpg",
    "name": "Nachos",
    "family": "GENERAL",
    "keywords": [
      "nachos"
    ],
    "cuisine": [
      "global"
    ],
    "category": [
      "starter"
    ],
    "dietary": "vegetarian",
    "suitableFor": [
      "grazing-table"
    ],
    "isValidQuality": true,
    "fileSizeBytes": 166434,
    "source": "generated",
    "generatedAt": "2026-09-02T08:35:25.723Z",
    "provider": "antigravity"
  },
  {
    "id": "dish-0046",
    "dishId": "dish-0046",
    "filename": "generated/dish-0046.jpg",
    "name": "Avocado salsa",
    "family": "GENERAL",
    "keywords": [
      "avocado",
      "salsa"
    ],
    "cuisine": [
      "global"
    ],
    "category": [
      "starter"
    ],
    "dietary": "vegetarian",
    "suitableFor": [
      "grazing-table"
    ],
    "isValidQuality": true,
    "fileSizeBytes": 116774,
    "source": "generated",
    "generatedAt": "2026-09-02T08:35:25.723Z",
    "provider": "antigravity"
  },
  {
    "id": "dish-0047",
    "dishId": "dish-0047",
    "filename": "generated/dish-0047.jpg",
    "name": "Sour cream",
    "family": "GENERAL",
    "keywords": [
      "sour",
      "cream"
    ],
    "cuisine": [
      "global"
    ],
    "category": [
      "starter"
    ],
    "dietary": "vegetarian",
    "suitableFor": [
      "grazing-table"
    ],
    "isValidQuality": true,
    "fileSizeBytes": 88941,
    "source": "generated",
    "generatedAt": "2026-09-02T08:35:25.723Z",
    "provider": "antigravity"
  },
  {
    "id": "dish-0048",
    "dishId": "dish-0048",
    "filename": "generated/dish-0048.jpg",
    "name": "Tomato salsa",
    "family": "GENERAL",
    "keywords": [
      "tomato",
      "salsa"
    ],
    "cuisine": [
      "global"
    ],
    "category": [
      "starter"
    ],
    "dietary": "vegetarian",
    "suitableFor": [
      "grazing-table"
    ],
    "isValidQuality": true,
    "fileSizeBytes": 112432,
    "source": "generated",
    "generatedAt": "2026-09-02T08:35:25.723Z",
    "provider": "antigravity"
  },
  {
    "id": "dish-0049",
    "dishId": "dish-0049",
    "filename": "generated/dish-0049.jpg",
    "name": "Mushroom paté",
    "family": "GENERAL",
    "keywords": [
      "mushroom",
      "pate"
    ],
    "cuisine": [
      "global"
    ],
    "category": [
      "starter"
    ],
    "dietary": "vegetarian",
    "suitableFor": [
      "grazing-table"
    ],
    "isValidQuality": true,
    "fileSizeBytes": 137471,
    "source": "generated",
    "generatedAt": "2026-09-02T08:35:25.723Z",
    "provider": "antigravity"
  },
  {
    "id": "dish-0050",
    "dishId": "dish-0050",
    "filename": "generated/dish-0050.jpg",
    "name": "Peri peri hummus",
    "family": "GENERAL",
    "keywords": [
      "peri",
      "hummus"
    ],
    "cuisine": [
      "global"
    ],
    "category": [
      "starter"
    ],
    "dietary": "vegetarian",
    "suitableFor": [
      "grazing-table"
    ],
    "isValidQuality": true,
    "fileSizeBytes": 148156,
    "source": "generated",
    "generatedAt": "2026-09-02T08:35:25.723Z",
    "provider": "antigravity"
  },
  {
    "id": "dish-0051",
    "dishId": "dish-0051",
    "filename": "generated/dish-0051.jpg",
    "name": "Camembert",
    "family": "GENERAL",
    "keywords": [
      "camembert"
    ],
    "cuisine": [
      "global"
    ],
    "category": [
      "starter"
    ],
    "dietary": "vegetarian",
    "suitableFor": [
      "grazing-table"
    ],
    "isValidQuality": true,
    "fileSizeBytes": 131833,
    "source": "generated",
    "generatedAt": "2026-09-02T08:35:25.723Z",
    "provider": "antigravity"
  },
  {
    "id": "dish-0052",
    "dishId": "dish-0052",
    "filename": "generated/dish-0052.jpg",
    "name": "Brie cheese",
    "family": "GENERAL",
    "keywords": [
      "brie",
      "cheese"
    ],
    "cuisine": [
      "global"
    ],
    "category": [
      "starter"
    ],
    "dietary": "vegetarian",
    "suitableFor": [
      "grazing-table"
    ],
    "isValidQuality": true,
    "fileSizeBytes": 105462,
    "source": "generated",
    "generatedAt": "2026-09-02T08:35:25.723Z",
    "provider": "antigravity"
  },
  {
    "id": "dish-0053",
    "dishId": "dish-0053",
    "filename": "generated/dish-0053.jpg",
    "name": "Red cheddar cheese",
    "family": "GENERAL",
    "keywords": [
      "red",
      "cheddar",
      "cheese"
    ],
    "cuisine": [
      "global"
    ],
    "category": [
      "starter"
    ],
    "dietary": "vegetarian",
    "suitableFor": [
      "grazing-table"
    ],
    "isValidQuality": true,
    "fileSizeBytes": 126581,
    "source": "generated",
    "generatedAt": "2026-09-02T08:35:25.723Z",
    "provider": "antigravity"
  },
  {
    "id": "dish-0054",
    "dishId": "dish-0054",
    "filename": "generated/dish-0054.jpg",
    "name": "Assorted fruits",
    "family": "GENERAL",
    "keywords": [
      "assorted",
      "fruits"
    ],
    "cuisine": [
      "global"
    ],
    "category": [
      "starter"
    ],
    "dietary": "vegetarian",
    "suitableFor": [
      "grazing-table"
    ],
    "isValidQuality": true,
    "fileSizeBytes": 120757,
    "source": "generated",
    "generatedAt": "2026-09-02T08:35:25.723Z",
    "provider": "antigravity"
  },
  {
    "id": "dish-0055",
    "dishId": "dish-0055",
    "filename": "generated/dish-0055.jpg",
    "name": "Pesto bruschetta",
    "family": "GENERAL",
    "keywords": [
      "pesto",
      "bruschetta"
    ],
    "cuisine": [
      "global"
    ],
    "category": [
      "starter"
    ],
    "dietary": "vegetarian",
    "suitableFor": [
      "grazing-table",
      "appetizer-rotation",
      "passed-hors",
      "arrival-bites"
    ],
    "isValidQuality": true,
    "fileSizeBytes": 172069,
    "source": "generated",
    "generatedAt": "2026-09-01T08:40:36.226Z",
    "provider": "antigravity",
    "model": "mock-svg-v1",
    "promptVersion": "v1.0"
  },
  {
    "id": "dish-0172",
    "dishId": "dish-0172",
    "filename": "generated/gulab-jamun.jpg",
    "name": "Gulab jamun",
    "family": "DESSERT",
    "keywords": [
      "gulab",
      "jamun"
    ],
    "cuisine": [
      "indian",
      "western",
      "north-indian"
    ],
    "category": [
      "dessert"
    ],
    "dietary": "vegetarian",
    "suitableFor": [
      "indian-desserts",
      "dessert-counter",
      "dessert"
    ],
    "isValidQuality": true,
    "fileSizeBytes": 796746,
    "source": "generated"
  },
  {
    "id": "dish-0639",
    "dishId": "dish-0639",
    "filename": "generated/paneer-tikka.jpg",
    "name": "Paneer tikka",
    "family": "PANEER",
    "keywords": [
      "paneer",
      "tikka"
    ],
    "cuisine": [
      "north indian",
      "global",
      "indian",
      "north-indian",
      "mughlai"
    ],
    "category": [
      "starter",
      "main-course"
    ],
    "dietary": "vegetarian",
    "suitableFor": [
      "appetizer-rotation",
      "passed-hors",
      "arrival-bites",
      "starter",
      "indian-counter",
      "mughlai-counter",
      "live-counter",
      "tandoor-counter"
    ],
    "isValidQuality": true,
    "fileSizeBytes": 787001,
    "source": "generated"
  },
  {
    "id": "sushi-platter",
    "filename": "generated/sushi-platter.jpg",
    "name": "Sushi Platter",
    "family": "SUSHI",
    "keywords": [
      "sushi",
      "platter"
    ],
    "cuisine": [
      "japanese",
      "asian"
    ],
    "category": [
      "sushi",
      "starter",
      "main-course",
      "seafood"
    ],
    "dietary": "seafood",
    "suitableFor": [
      "japanese-counter",
      "sushi-counter",
      "hero",
      "live-counter",
      "section-divider"
    ],
    "isValidQuality": true,
    "fileSizeBytes": 720651,
    "source": "generated"
  }
];

export default IMAGE_REGISTRY;
